"""fix channel foreign key error

Revision ID: 2c6afcb1a3df
Revises: c803863b97c6
Create Date: 2024-08-12 17:29:28.186116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c6afcb1a3df'
down_revision = 'c803863b97c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('sensor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'channel', ['channel_id'], ['channel'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sensor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
